### ISSUE TITLE
Problem with RecyclerView not rendering the progress.

### ISSUE THREAD

**Issue by fnk0** [akexorcist/Android-RoundCornerProgressBar#11]
So.. I'm using CardsLib with a CardRecyclerViewList and I'm having problems with the rendering of the ProgressBar. 

The only elements that get rendered are the elements that are visible on the first screen. But as I scroll down all of the remaining cards only show a grey background. 

![unnamed](https://cloud.githubusercontent.com/assets/4286642/6763154/dc11fdde-cf3e-11e4-8508-5b2c994b2429.png)

**Comment by goonerDroid** [comment]
Same here.Any solution yet?

**Comment by dev-myatminsoe** [comment]
same here. Still have errors with listview too.

**Comment by akexorcist** [comment]
I update latest version (1.2.0) and fix some problem about this view when using on adapter view. But it still have some bug, I will fix it later.

**Comment by fnk0** [comment]
@akexorcist it worked! At least for me. Once I updated to 1.2 it rendered fine. Thanks for the update!! :+1:

**Comment by caesarleong** [comment]
@akexorcist I found the setProgress() will not draw properly in ListView when the convertView is null in getView(). it will always  draw whole progress bar even the getProgress return a value which is not equal to rcMax. Looking forward your fix. Thanks for your effort!!!

**Comment by derohimat** [comment]
i found same problem in header list, not renderer data

![bug rounded progressbar](https://cloud.githubusercontent.com/assets/3787041/8203845/d6649b4c-150e-11e5-964c-caaca3c53899.png)

**Comment by 495055772** [comment]
Same here.Any solution yet?

**Comment by akexorcist** [comment]
I update latest library version. Update your code to using version 2.0.2 and check it again. I've already fix this render problem.

**Comment by caesarleong** [comment]
Thank akexorcist! It works perfectly
