### ISSUE TITLE
Progress not showing after VISIBLE from GONE

### ISSUE THREAD

**Issue by tzanou** [akexorcist/Android-RoundCornerProgressBar#12]
When I set GONE visibility on the progressbar or the surrounding layout ,when visibility is set back to visible progress is not showing.Working normaly when INVISIBLE and back to VISIBLE ,but with GONE has a problem

**Comment by akexorcist** [comment]
Latest version library. I've try to set visibility and it work well. Please check your problem. If you still has a problem please tell me how you design that layout. So I will test and fix for you.

**Comment by tzanou** [comment]
Works fine! great job thank you very much! :D
