### ISSUE TITLE
Parcelable error when reloading app back from stack and has been cleared by the os

### ISSUE THREAD

**Issue by sutharsha** [akexorcist/Android-RoundCornerProgressBar#19]
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@1b179a5d: Unmarshalling unknown type code 7471204 at offset 1112

STR:
Enable Don't keep activities in Developer options. Start the app and go to activity with the rc progressbar.
Get out of app and go back to it. crash.

From what i gathered 
Happens due to progaurd

Need to add

-keepclassmembers class \* implements android.os.Parcelable {
    static *\* CREATOR;
}

in progaurd-rules

**Comment by ivannarino** [comment]
It should be fixed with this #16 
Idk why @akexorcist hasn't accepted the PR yet as Travis says the build passed
