### ISSUE TITLE
Fix low version compatibility

### ISSUE THREAD

**Issue by darktiny** [akexorcist/Android-RoundCornerProgressBar#2]
Method "removeOnGlobalLayoutListener" is API Level 16

Method "setProgressColor" in RoundCornerProgressBar class is wrong.

```
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
    layoutBackground.setBackground(gradient);
} else {
    layoutBackground.setBackgroundDrawable(gradient);
}
```

Please fix it.

Nice library. Thx.

**Comment by GinRyan** [comment]
Very nice.

**Comment by akexorcist** [comment]
Arrr. I fotget it. Thanks guy!!

I will fix this with new library feature.

**Comment by first087** [comment]
I fixed it and create pull request for @akexorcist

**Comment by akexorcist** [comment]
v1.1.0 is coming! Check it out!
