### ISSUE TITLE
Start of progress bar is "flattened" during first ~10% of progress

### ISSUE THREAD

**Issue by TheIcemanCometh** [akexorcist/Android-RoundCornerProgressBar#20]
I'm trying out the component, but for me, the first 10% or so of the progress shows the bar being flattened at the leading edge.  Once it gets to that 10% point and to the end (100%) it's fine, it just starts out flat.

Screencast : http://screencast.com/t/9pPW0k3cEVm

I am using 30dp radius.

**Comment by creator4ever** [comment]
+1

**Comment by YaphetZhao** [comment]
+1

**Comment by ashish-bahl** [comment]
+1
