### ISSUE TITLE
Add minSdkVersion  to library

### ISSUE THREAD

**Issue by aminelaadhari** [akexorcist/Android-RoundCornerProgressBar#22]
Please add minSdkVersion to library because of the strange beahviour described in the following stackoverflow discussion:
http://stackoverflow.com/questions/27490598/why-does-my-app-has-the-read-phone-state-permission-although-its-not-declared-i

I just experienced this when upgrading from 1.0.0 to 1.2.0

Thanks !

**Comment by akexorcist** [comment]
I added it on version 1.2.3
Please update and check this issue again

**Comment by aminelaadhari** [comment]
Fixed. Thanks !
