### ISSUE TITLE
add textview with te percentatge number inside progressbar

### ISSUE THREAD

**Issue by Spiderbezno** [akexorcist/Android-RoundCornerProgressBar#23]
Is it possible add a textview or a text inside the progressbar to show the percentage number?

**Comment by akexorcist** [comment]
Sorry It's not support on this library

**Comment by chnouman** [comment]
please suppor this

**Comment by akexorcist** [comment]
In latest version, you can use `TextRoundCornerProgressBar` to show any text inside the progress
