### ISSUE TITLE
1.2.4 gradle release

### ISSUE THREAD

**Issue by rafalzawadzki** [akexorcist/Android-RoundCornerProgressBar#29]
Hello, will be gradle repo available for 1.2.4 release?

**Comment by Spiderbezno** [comment]
I have an error for version 1.2.3 and 1.2.4 that say that doesn't exits

**Comment by rafalzawadzki** [comment]
Yup, because these releases are not pushed to maven repo. You could try jitpack.io but I have had problems with building so idk if you can make it.

**Comment by akexorcist** [comment]
@rafalzawadzki  @Spiderbezno  It's available now. Sorry for lately.

**Comment by rafalzawadzki** [comment]
@akexorcist thanks, 1.2.3 is syncing ok with gradle. Will release 1.2.4 be available too? It has important commit that fixes a bug which crashes my app for a bunch of users ;)

**Comment by akexorcist** [comment]
@rafalzawadzki  try 1.2.5

**Comment by rafalzawadzki** [comment]
@akexorcist 1.2.5 works fine, but the bug mentioned here: https://github.com/akexorcist/Android-RoundCornerProgressBar/issues/24 still exists but it was fixed with 1.2.4 commit. Am I missing something?

**Comment by akexorcist** [comment]
I've update gradle to 1.3.1 on version 2.0.2. If you have any problem about gradle version, please create new issue.

Thank you
