### ISSUE TITLE
com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar

### ISSUE THREAD

**Issue by LuiguiBalarezo** [akexorcist/Android-RoundCornerProgressBar#3]
Hi thanks for sharing the library.

I wonder
that in the version 'com.akexorcist: RoundCornerProgressBar: 1.0.0' not found "TextRoundCornerProgressBar" class;
?

sorry for my bad English :)

**Comment by akexorcist** [comment]
I will update maven later big fixed :)

**Comment by akexorcist** [comment]
I added TextRoundCornerProgressBar class into my latest library.
