### ISSUE TITLE
No resource identifier found for attribute 'rcHeaderColor' 

### ISSUE THREAD

**Issue by Spiderbezno** [akexorcist/Android-RoundCornerProgressBar#30]
With last version(2.0.2), who is the new attribute name

**Comment by Spiderbezno** [comment]
Maybe is this "app:rcIconBackgroundColor"?

**Comment by akexorcist** [comment]
Yeah, Sorry for changing it without any documentation. I will write a new instruction in soon. 

Here is a new attributes for 2.0.0 or later

RoundCornerProgressBar Attribute

``` rcProgress
rcSecondaryProgress
rcMax
rcRadius
rcBackgroundPadding
rcReverse
rcProgressColor
rcSecondaryProgressColor
rcBackgroundColor
```

Additional attribute for IconRoundCornerProgressBar

``` rcIconSrc
rcIconSize
rcIconWidth
rcIconHeight
rcIconPadding
rcIconPaddingLeft
rcIconPaddingRight
rcIconPaddingTop
rcIconPaddingBottom
rcIconBackgroundColor
```

Additional attribute for TextRoundCornerProgressBar

``` rcTextProgressColor
rcTextProgressSize
rcTextProgressMargin
rcTextProgress
```
