### ISSUE TITLE
there is no progress happening.

### ISSUE THREAD

**Issue by mdali92** [akexorcist/Android-RoundCornerProgressBar#31]
hi,

I'm trying to use your library to implement a loading bar. However, when I use settings like :
1) layout_width = "fill_parent" 
2)  layout weight = 1 along with layout_width = 0

I don't see any progress happening. Just an empty bar.

But when I explicitly put for example layout_width = 250dp , then it works without any problem. Here is a image of my layout xml :

http://imgur.com/3odBve4

Any suggestions? thank yoi

**Comment by mdali92** [comment]
I just realized that the issue with me using :

android:layout_width="0dp"
android:layout_weight="1"

on the parent linearlayout.. When I remove these attributes and put layout_width=wrap contecnt for the parent linear layout, it works fine even with the progress bar's width set a wrap content or fill parent..

but I can't really do without the layout_wight attributes of the parent linearlayouts as other view's placement depends on it... Any suggestions?

**Comment by akexorcist** [comment]
My latest library version is 2.0.3. Please update and try again.

**Comment by mdali92** [comment]
Yup! It's working! Thanks!
