### ISSUE TITLE
Corners still showing up even radius set , 

### ISSUE THREAD

**Issue by saiidabs** [akexorcist/Android-RoundCornerProgressBar#32]
im using  2.0.2, since its the only one that worked properly, but im having problems with corners, even when the radius is set, the bars corners do change by the bars view itself has corners , not sure how to get rid of it, i tried changing the background of it to transparent but does nothing ,

**Comment by akexorcist** [comment]
Do you have any problem sample image?

**Comment by saiidabs** [comment]
in my class :

RoundCornerProgressBar progress1 = (RoundCornerProgressBar) getActivity().findViewById(R.id.progress_1);

        progress1.setProgressColor(Color.parseColor("#FF1F9B96"));
        progress1.setBackgroundColor(Color.parseColor("#FFA7A2A2"));
        progress1.setSecondaryProgressColor(Color.parseColor("#FFFF0000"));

        progress1.setMax(dObj.floatValue());
        progress1.setProgress(rm.floatValue());
        progress1.setSecondaryProgress(150);

in the xml view :
          <com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar
              android:id="@+id/progress_1"
              android:layout_height="40dp"
              android:layout_width="350dp"
              app:rcBackgroundPadding="10dp"
              app:rcRadius="20dp"
              android:layout_gravity="center"
              android:background="@android:color/white" />


and it looks like this :
http://i.imgur.com/qwbUcir.png

**Comment by saiidabs** [comment]
figured out that setting the colors in the activity cause the problem, i set the colors in the xml it works

**Comment by akexorcist** [comment]
I change setBackgroundColor to setProgressBackgroundColor. Sorry for inconvenient, I don't have a much time to update an instruction now. I'll update it later.
