### ISSUE TITLE
app:rcBackgroundRadius="dimension" not working in IconRoundCornerProgressBar

### ISSUE THREAD

**Issue by AndreiD** [akexorcist/Android-RoundCornerProgressBar#35]
settting radius on IconRoundCornerProgressBar doens't work

Error:(52) No resource identifier found for attribute 'rcBackgroundRadius' in package 'xxxxx'

guess you forgot to add one line of code somewhere :)

**Comment by akexorcist** [comment]
I changed from rcBackgroundRadius to rcRadius. Sorry for old description, I've no time to update it.
