### ISSUE TITLE
Use as SeekBar

### ISSUE THREAD

**Issue by Mithrandir21** [akexorcist/Android-RoundCornerProgressBar#37]
Is it possible to use this libraries ProgressBar as a SeekBar?
If it's not a built in feature, how easy would it be to implement such a ability?

**Comment by akexorcist** [comment]
Sorry, but this library isn't build for usage or implement to a seekbar.

**Comment by Mithrandir21** [comment]
Ok. Thank you for the direct reply that definitely saved me a lot of testing time.
But if someone was to attempt to implement such a feature to a fork of this library, would you have suggestions, advice, tips, starting points or ideas about it?
I've done a lot of work on touch listeners and UI updates before, so I might fork and give it a try.

**Comment by Mithrandir21** [comment]
I forked the library and added Touch seeking functionality.
Created a Pull Request https://github.com/akexorcist/Android-RoundCornerProgressBar/pull/38 with details and comments.
The fork worked great for me, so I wanted to share my added functionality back to this helpful library.
