### ISSUE TITLE
Centered Progress Bar

### ISSUE THREAD

**Issue by redsanso** [akexorcist/Android-RoundCornerProgressBar#42]
Hello, I made a temporary implementation while waiting for the request to be evaluated.
This is a simple tutorial in which you will need to create some custom files.
## Step 1 : setup

Create a class with a custom name. In example, let's say **CenteredProgressBar.java**.
What you need is:
- to extend com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar:
  
  ``` java
  import com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar;
  
  public class CenteredProgressBar extends RoundCornerProgressBar {
  
  }
  ```
- to create two constructors matching super class:
  
  ``` java
  
  public CenteredProgressBar(Context context, AttributeSet attrs) {
      super(context, attrs);
  }
  
  public CenteredProgressBar(Context context, AttributeSet attrs, int defStyleAttr) {
      super(context, attrs, defStyleAttr);
  }
  ```
  
  since @akexorcist uses them both and we need to use them
- to override the _drawProgress_ method, using MarginLayoutParams to simulate a left margin equal to _(max width - current width) / 2_:
  
  ``` java
  @SuppressWarnings("deprecation")
  @Override
  protected void drawProgress(LinearLayout layoutProgress, float max, float progress, float totalWidth,
                              int radius, int padding, int colorProgress, boolean isReverse) {
  
      super.drawProgress(layoutProgress, max, progress, totalWidth, radius, padding, colorProgress, isReverse);
      MarginLayoutParams params = (MarginLayoutParams) layoutProgress.getLayoutParams();
  
      float ratio = max / progress;
      float progressWidth = (totalWidth - (padding * 2)) / ratio;
      float deltaWidth = totalWidth - progressWidth;
  
      params.setMargins((int) (deltaWidth / 2), params.topMargin, (int) (deltaWidth / 2), params.bottomMargin);
      layoutProgress.setLayoutParams(params);
  }
  ```
## Step 2 : use it!

It's simple! Just call your custom object in your layout.

``` xml
<com.your.app.package.CenteredProgressBar
                    android:layout_width="80dp"
                    android:layout_height="8dp"
                    android:layout_gravity="center_horizontal|center_vertical"
                    android:layout_margin="8dp"
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    app:rcBackgroundPadding="1dp"
                    app:rcBackgroundColor="#000000"
                    app:rcProgress="0.3"
                    app:rcMax="1" />
```
## Demo

Here is an example. The grey background is from my external layout, you would not see it if you copy paste.

![aaa](https://cloud.githubusercontent.com/assets/4395762/13035026/8f6b48bc-d345-11e5-95ab-84bab7832039.png)

**_The gradient bar color is explained in another issue:_** https://github.com/akexorcist/Android-RoundCornerProgressBar/issues/39

I would like to give my thanks to @akexorcist for his awesome work. It really boosted my app development!

**Comment by akexorcist** [comment]
@redsanso Hey! That's very interesting! Can you send pull request for this commit to me? I will merge into my library and give special thanks to you in this source code.

**Comment by akexorcist** [comment]
Add CenteredRoundCornerProgressBar in 2.1.0 (see https://github.com/akexorcist/Android-RoundCornerProgressBar/commit/e554e152b75fd4a5699e39cc77d8697385121e48)

Thank you so much again, @redsanso
