### ISSUE TITLE
Can't build TextRoundCornerProgressBar

### ISSUE THREAD

**Issue by IonAalbers** [akexorcist/Android-RoundCornerProgressBar#43]
Included com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar into xml.

```
compile 'com.akexorcist:RoundCornerProgressBar:2.0.3'
classpath 'com.android.tools.build:gradle:1.5.0'
buildToolsVersion '23.0.2'


Warning: com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$2: can't find referenced method 'android.widget.TextView access$000(com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar)' in program class com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar
Warning: com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar$2: can't find enclosing method 'void setTextProgressAlign()' in program class com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar

```

**Comment by HarryMMR** [comment]
i also have same error after I enabled proguard (minifyEnabled true). Please suggest how to fix.

**Comment by tianyong2** [comment]
i also have same error after I enabled proguard (minifyEnabled true). Please suggest how to fix.

**Comment by Warpath** [comment]
i also have same error after I enabled proguard (minifyEnabled true). Please suggest how to fix.

**Comment by GaryLaurenceau** [comment]
I temporally fixed this bug by adding a line to my proguard file:

```
-dontwarn com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar
```

**Comment by MMnasrabadi** [comment]
tanks

**Comment by muhammadzadeh** [comment]
i also have same error after I enabled proguard (minifyEnabled true). Please suggest how to fix.

**Comment by JavierLiu** [comment]
also met this issue and resolved by adding 
"-dontwarn com.akexorcist.roundcornerprogressbar.TextRoundCornerProgressBar" in proguard-rules.pro
