### ISSUE TITLE
Can't roundcornerprogressbar programmatically

### ISSUE THREAD

**Issue by mutkan** [akexorcist/Android-RoundCornerProgressBar#44]
Hi,

I think we cannot add roundcornerprogressbar programmatically? Am i right? There is no roundcornerprogressbar(Context ctx).

**Comment by ghost** [comment]
Hello!
You can actually. Just throw 'null' as second parameter when initializing progressbar. Look at the snippet below I tested to create one programmatically. Cheers!

---

RelativeLayout relativeLayout = new RelativeLayout(this);
RoundCornerProgressBar progressBar = new RoundCornerProgressBar(this, null);

progressBar.setRadius(10);
progressBar.setPadding(0);
progressBar.setMax(5000);
progressBar.setProgress(2500);

progressBar.setProgressBackgroundColor(getResources().getColor(R.color.colorAccent));
progressBar.setProgressColor(getResources().getColor(R.color.colorPrimary));

RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT);

params.leftMargin = 50;
params.topMargin = 50;
params.width = 350;
params.height = 90;
progressBar.setLayoutParams(params);

relativeLayout.addView(progressBar);
