### ISSUE TITLE
How to emulate android:indeterminate?

### ISSUE THREAD

**Issue by The28AWG** [akexorcist/Android-RoundCornerProgressBar#46]
Hello!
How to emulate android:indeterminate?
[http://www.materialdoc.com/content/images/2015/11/intro-v1.gif](http://www.materialdoc.com/content/images/2015/11/intro-v1.gif)

**Comment by akexorcist** [comment]
Sorry, Indeterminate isn't available for this library.

**Comment by comeback4u** [comment]
Any plans to adding Indeterminate in this library?

**Comment by akexorcist** [comment]
@comeback4u Not yet now

**Comment by akexorcist** [comment]
Added `IndeterminateRoundProgressBar` and `IndeterminateCenteredRoundProgressBar` for emulate the indeterminate 

See https://github.com/akexorcist/Android-RoundCornerProgressBar/commit/69f9604b34f400132baabcd6e34edd6c23b1e784
