### ISSUE TITLE
Icon bug

### ISSUE THREAD

**Issue by XxGoliathusxX** [akexorcist/Android-RoundCornerProgressBar#47]
I created an IconProgressBar. If I start the activity the icon is show very big for like a half second in the middle of the screen and dissapears then. This looks awful.

**Comment by anwar3606** [comment]
I can't even set the icon. I can't even find setIconResource function

**Comment by XxGoliathusxX** [comment]
Be sure to implement IconProgressbar in the layout and also in the code!

**Comment by akexorcist** [comment]
@XxGoliathusxX  Sorry for very very very lately reply

Could you provide more information about how do you implement the library in your code? I can't reproduce this issue
