### ISSUE TITLE
Attribute "..." has already been defined

### ISSUE THREAD

**Issue by FHellmann** [akexorcist/Android-RoundCornerProgressBar#5]
When I want to build my project only with the gradle addition of your project I receive the following errors...

``` java
\app\build\intermediates\res\debug\values\values.xml:497: error: Attribute "progress" has already been defined

\app\build\intermediates\res\debug\values\values.xml:497: error: Attribute "max" has already been defined

\app\build\intermediates\res\debug\values\values.xml:497: error: Attribute "iconSize" has already been defined

\app\build\intermediates\res\debug\values\values.xml:497: error: Attribute "iconPadding" has already been defined
```

Maybe add a prefix to all your custom attributes?

**Comment by first087** [comment]
I fixed it.

![2015-02-12 16 24 51](https://cloud.githubusercontent.com/assets/6030102/6165112/ea463a88-b2d7-11e4-9231-095abd9d83a3.jpg)

**Comment by FHellmann** [comment]
@akexorcist When do you think, you release a new version with this fixed issue?

**Comment by akexorcist** [comment]
@FHellmann  I already merge a code from @first087 but I didn't upload to maven yet

**Comment by FHellmann** [comment]
@akexorcist when do you think you upload a new version with this fixed issue to maven?

**Comment by dadino** [comment]
@akexorcist an hotfix release for this issue would be appreciated.

**Comment by carstenhag** [comment]
:+1: 

![1](https://i.imgur.com/EhkCQof.png)

**Comment by akexorcist** [comment]
@FHellmann  @dadino  @Moter8 
i've updated new library version to maven. please check it again.
Thanks! @first087
