### ISSUE TITLE
Progress bar does not move ahead

### ISSUE THREAD

**Issue by Sutirth** [akexorcist/Android-RoundCornerProgressBar#54]
I have set rcMax as  app:rcMax="10000"

and when I try to set progress such as 6000 the progress bar is stuck at a level of 5000

**Comment by akexorcist** [comment]
What kind of progress bar do you use? Could you provide more information or code

Because it's work fine in my test code

```xml
<com.akexorcist.roundcornerprogressbar.RoundCornerProgressBar
        android:id="@+id/progressBar"
        android:layout_width="250dp"
        android:layout_height="40dp"
        app:rcMax="10000"
        app:rcProgress="5000"
        app:rcProgressColor="#E91E63" />
```

```kotlin
fun onButtonClick() {
    progressBar.progress = 6000f
}
```

**Comment by Sutirth** [comment]
Closing it since I asked this question 4 years ago and I dont remember it now
