### ISSUE TITLE
drawPrimaryProgress called twice with same parameters

### ISSUE THREAD

**Issue by thedoppel** [akexorcist/Android-RoundCornerProgressBar#55]
Hi,

In onSizeChanged, there are 2 calls to drawPrimaryProgress with same parameters. The calls are on different threads , if I remove one of them the progress is not drawn.  Why does the postDelayed needed? Why doesnt the first call take effect? I am asking because the postDelayed call causes an unwanted blink.

Thanks.

**Comment by akexorcist** [comment]
when call `drawPrimaryProgress(...)` in `onSizeChanged(..)`, there is no effect with UI rendering in child view (primary and secondary progress are child views)

Refer to https://stackoverflow.com/questions/14345287/requestlayout-has-no-effect-when-called-from-onsizechanged

But as you say called twice is bad. So call once in post method  without any delayed in my last commit
