### ISSUE TITLE
add marker to secondary progress

### ISSUE THREAD

**Issue by hidayatasep43** [akexorcist/Android-RoundCornerProgressBar#62]
Hello . 
I'm making progress bar. I want to add an image to mark secondary progress but I dont know to make it. Please help me :)

![image](https://user-images.githubusercontent.com/17679875/28101401-788651cc-66f2-11e7-9174-6fb2bc54d55d.png)

**Comment by akexorcist** [comment]
You can custom your own progress bar with marker by extends the BaseRoundCornerProgressBar or AnimatedRoundCornerProgressBar. And put your logic to measure the position of marker in `drawProgress(...)`
