### ISSUE TITLE
Problem for Rounded Progress Bar on Jelly Bean Devices 

### ISSUE THREAD

**Issue by Suyash171** [akexorcist/Android-RoundCornerProgressBar#63]
![screenshot_2017-11-03-10-50-56 1](https://user-images.githubusercontent.com/31531769/32361648-7041c678-c088-11e7-9e48-4f025abd23cd.png)
 
Hello, i use Rounded progress bar to show progress, but it does not works properly below android Jelly Bean 4.2.2  and below devices,
the progress bar gets stretch

**Comment by szamelsz** [comment]
Same problem here.

**Comment by behelit** [comment]
Works for me on 4.2.2
Test the sample app on Google Play
and show your code

**Comment by Suyash171** [comment]
@behelit  sample app  is not available on play store
"We're sorry, the requested URL was not found on this server."

**Comment by behelit** [comment]
https://play.google.com/store/apps/details?id=com.akexorcist.roundcornerprogressbar

This one

**Comment by Suyash171** [comment]
> https://play.google.com/store/apps/details?id=com.akexorcist.roundcornerprogressbar
> 
> This one

Okay Thank you
