### ISSUE TITLE
Icon rcProgressBar Not displaying progress at all

### ISSUE THREAD

**Issue by zach-morgan** [akexorcist/Android-RoundCornerProgressBar#67]
So I have been working with the library for a little bit and I can't get progress to show on the icon progress bar. It works perfectly fine for all other versions of the bar. For example, this code snippet is directly from the example code, and the progress displays correctly when I switch it to just a RoundCornerProgressBar, but once I add the Icon in, it displays the colors and everything else correctly, but shows no progress..
`<com.akexorcist.roundcornerprogressbar.IconRoundCornerProgressBar
        android:layout_width="250dp"
        android:layout_height="30dp"
        android:layout_marginBottom="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:rcBackgroundColor="@color/white"
        app:rcBackgroundPadding="2dp"
        app:rcMax="100"
        app:rcProgress="50"
        app:rcProgressColor="@color/murica_flag_blue"
        app:rcRadius="0dp" />`

**Comment by 1-riverfish** [comment]
Same question，solved？

**Comment by tranleduy2000** [comment]
There is a bug of this library, `ivProgressIcon` layouts incorrectly in `IconRoundCornerProgressBar.java`
Before call `setProgress` and `setMax` methods, you must layout this view
```Java
       progressView.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED);
       progressView.layout(0, 0, progressView.getWidth(), progressView.getHeight());
```

**Comment by akexorcist** [comment]
Icon size attribute is required
```xml
app:rcIconSize="dimension"
```
