### ISSUE TITLE
IndeterminateRoundCornerProgressBar How to control the number of animation executions   

### ISSUE THREAD

**Issue by xyZangGit** [akexorcist/Android-RoundCornerProgressBar#76]

**Comment by akexorcist** [comment]
Do you have any use case to control the number of animation executions?

**Comment by xyZangGit** [comment]
Sorry, maybe I had a problem with my original description. How do I control the number of animations

**Comment by xyZangGit** [comment]
> Do you have any use case to control the number of animation executions?

Sorry, maybe I had a problem with my original description. How do I control the number of animations

**Comment by akexorcist** [comment]
It cannot do that right now. Can you give some suggestion? If you want to control it, how it should be?
