### ISSUE TITLE
Progressbar freezes after reload

### ISSUE THREAD

**Issue by drisul10** [akexorcist/Android-RoundCornerProgressBar#77]
Hi, @akexorcist. Why my progressBar (I mean indeterminate progressbar) is freezing after I reloading the fragment (which is technically I set progressBar view gone and then I set it to visible)? Or maybe any advice from you to handle progressBar (show and hide) will be appreciated.

**Comment by akexorcist** [comment]
Cause of problem is using onWindowVisibilityChanged instead of onVisibilityChanged in the library. When you change the visibility. It's about view's visibility changes, not window.

Thank you for your feedback. I fixed and tested it. Please waiting for version 1.2.1.

**Comment by akexorcist** [comment]
@leosird 2.1.1 is out with issue fixed. 

Feel free to reopen this issue if it still happen.
