### ISSUE TITLE
If height is not wrap_content it doesnt not show progress

### ISSUE THREAD

**Issue by evanli2** [akexorcist/Android-RoundCornerProgressBar#78]
I am not sure if this is intended or not, but I just copy and pasted your first example and the progress doesn't show unless I make it wrap_content.

![aa2](https://user-images.githubusercontent.com/27339162/84979852-4fbce400-b0e5-11ea-8a0c-572ad2da34f2.png)

**Comment by bryan-ibrahim** [comment]
Years later still no fix to this, a hack around this would be to specify the _rcIconHeight_. Other than that, I found this library to be better -> [AnimatedProgressBar](https://github.com/mckrpk/AnimatedProgressBar), I have no affiliation to it

**Comment by akexorcist** [comment]
That was my intention because you can specific icon size (or height) and icon padding then view height will be sized according to the icon height and icon padding.

In your case, 
```xml
<com.akexorcist.roundcornerprogressbar.IconRoundCornerProgressBar
    android:layout:width="260dp"
    android:layout:width="wrap_content"
    app:rcIconSize="24dp"
    app:rcIconPadding="3dp"
    ... />
```

The code above will make the height to be 30dp
