### ISSUE TITLE
progress small

### ISSUE THREAD

**Issue by SuppanatThreerattananukul** [akexorcist/Android-RoundCornerProgressBar#82]
![image](https://user-images.githubusercontent.com/46100073/94777666-07a0a380-03ee-11eb-834d-82aed6deca6e.png)

**Comment by akexorcist** [comment]
That's what it should be because the value too less for render the progress as full size. 

See https://github.com/akexorcist/RoundCornerProgressBar/issues/74. To prevent this, I have to reduce the size of the progress when the value less than the possible size.
