### ISSUE TITLE
android.util.SuperNotCalledException: Activity {MainActivity} did not call through to super.onCreate()

### ISSUE THREAD

**Issue by maoai-xianyu** [akexorcist/Android-RoundCornerProgressBar#83]
java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Parcel;Ljava/lang/ClassLoader;)V in class Landroid/view/AbsSavedState; or its super classes (declaration of 'android.view.AbsSavedState' appears in /system/framework/framework.jar)
	03-08 08:08:54.781 22877 22877 W System.err: 	AnimatedRoundCornerProgressBar$a.<init>(MovieFile:341)
	03-08 08:08:54.781 22877 22877 W System.err: 	AnimatedRoundCornerProgressBar$a$1.a(MovieFile:364)
	03-08 08:08:54.781 22877 22877 W System.err: 
              AnimatedRoundCornerProgressBar$a$1.createFromParcel(MovieFile:361)

**Comment by maoai-xianyu** [comment]
AnimatedRoundCornerProgressBar  类中导入的是  import android.view.AbsSavedState;  当切换到 androidx 的时候，这个类没有改成  import androidx.customview.view.AbsSavedState； 不知道是不是这个触发的这个问题。

**Comment by akexorcist** [comment]
This look strange because my library using `androidx.customview.view.AbsSavedState`, not `android.view.AbsSavedState`

Please describe more information about your implementation.
- Library version
- Code implementation

A few stack trace isn't enough to investigate the problem
