### ISSUE TITLE
mavenCentral - missing 2.1.2

### ISSUE THREAD

**Issue by rafalmodrzynski** [akexorcist/Android-RoundCornerProgressBar#88]
Failed to resolve: com.akexorcist:RoundCornerProgressBar:2.1.2

https://search.maven.org/search?q=g:com.akexorcist%20a:RoundCornerProgressBar

last version is 2.0.3

**Comment by akexorcist** [comment]
@rafalmodrzynski Artifact has been moved to the new one. 

Please use `implementation 'com.akexorcist:round-corner-progress-bar:2.1.2'` instead

https://search.maven.org/artifact/com.akexorcist/round-corner-progress-bar
