### ISSUE TITLE
When padding is changed pragmatically it does not refresh the view

### ISSUE THREAD

**Issue by EugeneHoran** [akexorcist/Android-RoundCornerProgressBar#9]
To start, love the library.  I am changing the padding of the progressbar pragmatically and it does not refresh the view to match the progress.  How would I solve this issue.  I will post two photos of the issue. 

The progress bar is below the toolbar.  I have set the max to 100 and progress to 50
![device-2015-03-15-142740](https://cloud.githubusercontent.com/assets/7454787/6657329/92adf83c-cb1f-11e4-86a9-b24b5842769f.png)

Here is what the progress  bar looks like when I change the padding on the left and right of it.  
![device-2015-03-15-142816](https://cloud.githubusercontent.com/assets/7454787/6657344/bf35f65c-cb1f-11e4-9de2-572ecb1c7835.png)

**Comment by akexorcist** [comment]
Update to latest version and use .invalidate() when you change padding size. Thanks!

**Comment by EugeneHoran** [comment]
@akexorcist Awesome thank you!
